name: If Noah Than Noah
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5fee80ae-69b7-4ef0-8052-80fb018bc054.webp
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/932f8419-247c-4ce8-8c7f-3d875e935845.webp
layout_spectrum: 0.3567645503590713
typography_spectrum: 0.4048118818477534
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#E1E6FA'
    - '#C4D7ED'
    - '#ABC8E2'
    - '#375D81'
    - '#183152'
  brandStrength: 0.5576303628139604
  lightness: 0.1594648825424253
  saturation: 0.7849386234207097
  rhythmicContrast: 0.47616324297382984
purpose:
  - type: internal
    label: Helmy
    item: 745ea8c5-acd9-4739-921a-d400c198a853
  - type: internal
    label: Direct
    item: 745ea8c5-acd9-4739-921a-d400c198a853
title: Tech Logician
description: .
author:
  name: Noah M
  email: norelply@.com
content_rating:
  adult: false
navigation:
  - name: ' Birthday Wish'
    id: aa161e08-4493-44e3-bf9d-f7f9a6345da8
    type: content
  - name: Huawei ONT Critical Alert
    url: 'https://research.checkpoint.com/good-zero-day-skiddie/'
    type: external
  - name: Blueborne Spectrum
    id: ccd71dd6-b83e-494f-bd1f-3c081d511fb9
    type: content
  - name: Meltdown Spectrum
    url: 'https://meltdownattack.com'
    type: external
  - name: Encryption Flaw Telegram / Whatsapp
    id: 9a921659-5d20-40ea-8838-e7bd66f75c6b
    type: content
  - name: The Dreamer
    id: 745ea8c5-acd9-4739-921a-d400c198a853
    type: content
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://s3-us-west-2.amazonaws.com/the-grid-img/p/5dc325af3bcd09f509f1de18ae1168836f87f00a">
    src: >-
      https://s3-us-west-2.amazonaws.com/the-grid-img/p/5dc325af3bcd09f509f1de18ae1168836f87f00a
    metadata:
      '@type': MediaObject
      '@context': 'http://schema.org'
      keywords: []
      publisher:
        name: .s3-us-west-2.amazonaws.com
        domain: s3-us-west-2.amazonaws.com
        url: 'https://s3-us-west-2.amazonaws.com'
      author: []
      starred: false
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
github: true
