name: the typo king
layout_spectrum: 0.35965130798942824
typography_spectrum: 0.320400522869025
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  brandStrength: 0.41971812938137143
  lightness: 0.9407284944439029
  saturation: 0.8670675013190375
  rhythmicContrast: 0.15219430706214787
purpose:
  - type: internal
    label: Helmy
    item: 745ea8c5-acd9-4739-921a-d400c198a853
  - type: internal
    label: Direct
    item: 745ea8c5-acd9-4739-921a-d400c198a853
title: NOA'HOXY
description: If Noah Than Noah
author:
  name: mdno
content_rating:
  adult: false
navigation:
  - name: Huawei ONT Critical Alert
    url: 'https://research.checkpoint.com/good-zero-day-skiddie/'
    type: external
  - name: Meltdown Spectrum
    url: 'https://meltdownattack.com'
    type: external
  - name: Best Birthday Wish
    id: aa161e08-4493-44e3-bf9d-f7f9a6345da8
    type: content
  - name: Encryption Flaw Telegram / Whatsapp
    id: 9a921659-5d20-40ea-8838-e7bd66f75c6b
    type: content
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://s3-us-west-2.amazonaws.com/the-grid-img/p/5dc325af3bcd09f509f1de18ae1168836f87f00a">
    src: >-
      https://s3-us-west-2.amazonaws.com/the-grid-img/p/5dc325af3bcd09f509f1de18ae1168836f87f00a
    metadata:
      '@type': MediaObject
      '@context': 'http://schema.org'
      keywords: []
      publisher:
        name: .s3-us-west-2.amazonaws.com
        domain: s3-us-west-2.amazonaws.com
        url: 'https://s3-us-west-2.amazonaws.com'
      author: []
      starred: false
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
github: true
